### PR TITLE
Make rastertopos58 compatible with cups v2.3.1

### PR DESCRIPTION
**Pull request by alvaroordonhez**

### CODE REVIEW

**Comment by IntegersOfK** [comment]
Hi I didn't really make this driver, I just put the contents that I found from the CD years ago now. But I know a lot of people come here for these drivers so if you're saying this fixes compatibility with newer version of CUPS I will merge it.

**Comment by alvaroordonhez** [comment]
Hi! Yes, this modification fixes it. Ubuntu 20.04 comes with cups v2.3.1 and the original driver is not compatible without this little change.

**Comment by microhobby** [comment]
I tested the fix, and it works! Thanks @mustekito

**Comment by IntegersOfK** [comment]
Awesome, glad you were able to collaborate!

**Pull request merged**
